sonar.projectKey=infraguard-ml-predictor
sonar.projectName=InfraGuard ML Predictor
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/venv/**,**/mlflow-artifacts/**
sonar.coverage.exclusions=**/generate_data.py,**/train.py,**/promote_model.py
