sonar.projectKey=infraguard-drift-engine
sonar.projectName=InfraGuard Drift Engine
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**
sonar.coverage.exclusions=**/cmd/agent/main.go,**/agent/main.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
